In [3]:
import pandas as pd
import dask.dataframe as dd

In [2]:
last_gen = pd.read_csv('key_files/final_gen.csv')['sample_name']

In [ ]:
allele_freq = dd.read_csv('key_files/merged_hapFIRE_allele_frequency.txt', usecols = last_gen, sep = '\t')

allele_freq = allele_freq.compute() 

allele_freq = allele_freq.reset_index(drop=True)

In [6]:
fc = pd.read_csv('key_files/merged_sample_table.csv')

In [7]:
dict_snps = 'key_files/var_pos_grenenet.csv'
dict_snps = pd.read_csv(dict_snps)

In [8]:
mask_maf_05 = dict_snps['maf05filter'].notna()

In [9]:
mask_maf_05.sum()

1147892

In [10]:
dict_snps_filter = dict_snps[dict_snps['maf05filter'].notna()].drop(['maf05filter', 'total_alleles05filter'],axis=1).reset_index(drop=True)

In [11]:
allele_freq_f = allele_freq[mask_maf_05]

In [30]:
allele_freq_f = allele_freq_f.reset_index(drop=True)

In [31]:
allele_counts = {}
for sample in allele_freq_f.columns:
    flower_counts = fc[fc['sample_name'] == sample]['total_flower_counts'].values[0]
    allele_counts[sample] = allele_freq_f[sample] * flower_counts * 2

In [32]:
allele_counts = pd.concat(allele_counts,axis=1)

In [33]:
allele_counts

,1_2_2,1_2_3,1_3_1,1_3_4,1_3_5,1_3_6,1_3_7,1_3_8,1_3_9,1_3_10,...,60_1_3,60_1_4,60_1_5,60_1_6,60_1_7,60_1_8,60_1_9,60_1_10,60_1_11,60_1_12
0,132.491744,76.573060,35.847736,24.657826,50.272346,33.358798,21.016204,8.605536,4.154482,1.562488,...,10.70166,8.66862,14.392182,12.909016,9.825516,11.184828,9.218384,10.051496,19.13886,23.84366
1,20.956972,4.778906,0.291534,0.047952,25.679248,10.755136,1.842958,1.577334,5.064456,0.018356,...,1.69448,6.93800,0.919874,0.102972,0.384074,6.509400,0.227694,0.397474,3.42616,0.50508
2,47.954048,11.896680,3.004408,0.091058,18.021556,0.728198,136.791600,0.140270,0.987110,0.033860,...,1.55216,0.30766,0.225294,4.268392,0.382072,10.888026,0.162074,0.910896,3.86708,0.68784
3,4.347494,17.788984,0.098244,1.277300,12.378682,0.274534,2.171542,0.409492,1.821490,0.016328,...,3.88724,1.97350,4.324318,0.111140,0.100842,6.539352,0.722072,8.127938,7.32839,4.40598
4,4.347494,17.788984,0.098244,1.277300,12.378682,0.274534,2.171542,0.409492,1.821490,0.016328,...,3.88724,1.97350,4.324318,0.111140,0.100842,6.539352,0.722072,8.127938,7.32839,4.40598
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1147887,355.806736,215.241070,46.903026,36.335314,121.210006,86.062014,120.440210,15.814756,37.100550,7.958058,...,35.34594,28.71426,29.231036,28.379720,21.611646,43.179972,9.953188,32.958478,27.90320,32.65038
1147888,52.510172,6.711900,6.035960,0.053262,33.120638,16.839822,4.229996,2.339372,7.568266,1.422546,...,6.14798,9.16150,0.922764,4.460928,0.120518,2.781282,0.107892,3.906280,3.67044,0.37130
1147889,52.510172,6.711900,6.035960,0.053262,33.120638,16.839822,4.229996,2.339372,7.568266,1.422546,...,6.14798,9.16150,0.922764,4.460928,0.120518,2.781282,0.107892,3.906280,3.67044,0.37130
1147890,193.092150,91.708240,37.538794,14.333248,96.724936,41.596726,92.707092,12.275926,25.276028,3.209528,...,27.79496,12.16686,16.546102,5.784764,9.880918,35.992398,4.358798,15.254442,22.02774,14.14890
1147891,113.672688,63.948038,7.365270,2.964976,19.800308,1.145858,11.822338,2.554126,2.275756,0.008612,...,4.64776,11.04770,10.670536,17.218752,5.850200,4.519584,4.663510,12.540598,5.09140,9.53768

In [34]:
total_flowers_collected_last_gen = fc[fc['sample_name'].isin(last_gen)]['total_flower_counts'].sum()

In [35]:
total_flowers_collected_last_gen

22122

In [36]:
total_genomes_collected_last_gen = total_flowers_collected_last_gen * 2

In [ ]:
min_freq = 0.05
min_count = total_genomes_collected_last_gen * min_freq

min_count

total_alleles_sampled = allele_counts.sum(axis=1)

In [40]:
total_alleles_sampled

0          12943.107644
1           3277.879394
2           4419.393318
3           3040.856378
4           3040.856378
               ...
1147887    36437.691382
1147888     3288.663292
1147889     3288.663292
1147890    19830.838012
1147891     7764.982164
Length: 1147892, dtype: float64

In [41]:
total_alleles_sampled

0          12943.107644
1           3277.879394
2           4419.393318
3           3040.856378
4           3040.856378
               ...
1147887    36437.691382
1147888     3288.663292
1147889     3288.663292
1147890    19830.838012
1147891     7764.982164
Length: 1147892, dtype: float64

In [42]:
mask_min_counts = total_alleles_sampled > min_count

In [43]:
mask_min_counts

0          True
1          True
2          True
3          True
4          True
           ...
1147887    True
1147888    True
1147889    True
1147890    True
1147891    True
Length: 1147892, dtype: bool

In [44]:
total_alleles_sampled

0          12943.107644
1           3277.879394
2           4419.393318
3           3040.856378
4           3040.856378
               ...
1147887    36437.691382
1147888     3288.663292
1147889     3288.663292
1147890    19830.838012
1147891     7764.982164
Length: 1147892, dtype: float64

In [46]:
filtered_mincounts_snpid = dict_snps_filter[mask_min_counts]

In [51]:
filtered_mincounts_snpid.columns = ['filter_min_count_final_gen', 'pos', 'chrom']

In [53]:
dict_snps_filter = dict_snps_filter.merge(filtered_mincounts_snpid, how= 'outer')

In [55]:
dict_snps_filter['filter_min_count_final_gen'].dropna()

0               1_346
1               1_353
2               1_363
3               1_395
4               1_396
              ...
1147887    5_26975078
1147888    5_26975121
1147889    5_26975148
1147890    5_26975272
1147891    5_26975288
Name: filter_min_count_final_gen, Length: 1048635, dtype: object

In [56]:
dict_snps_filter

                 id       pos  chrom filter_min_count_final_gen
0             1_346       346      1                      1_346
1             1_353       353      1                      1_353
2             1_363       363      1                      1_363
3             1_395       395      1                      1_395
4             1_396       396      1                      1_396
...             ...       ...    ...                        ...
1147887  5_26975078  26975078      5                 5_26975078
1147888  5_26975121  26975121      5                 5_26975121
1147889  5_26975148  26975148      5                 5_26975148
1147890  5_26975272  26975272      5                 5_26975272
1147891  5_26975288  26975288      5                 5_26975288

[1147892 rows x 4 columns]

In [58]:
mask_min_counts

0          True
1          True
2          True
3          True
4          True
           ...
1147887    True
1147888    True
1147889    True
1147890    True
1147891    True
Length: 1147892, dtype: bool

In [35]:
mask_min_counts

1        True
4        True
5        True
6        True
7        True
        ...
6075    False
6076    False
6077    False
6078     True
6079     True
Length: 1329711, dtype: bool

In [60]:
allele_freq_f_maf_min_count = allele_freq_f[mask_min_counts]

In [64]:
var_pos_grenenet = pd.read_csv('key_files/var_pos_grenenet.csv')

In [67]:
var_pos_grenenet = var_pos_grenenet.merge(filtered_mincounts_snpid, how='outer')

In [69]:
var_pos_grenenet.columns = ['id', 'pos', 'chrom', 'maf05filter', 'total_alleles05filter_firstgen',
       'total_alleles05filter_lastgen']

In [71]:
var_pos_grenenet.to_csv('key_files/var_pos_grenenet.csv',index=None)

In [72]:
allele_freq_f_maf_min_count.to_csv('key_files/allele_freq_maf05_mincount05_lastgensamples.csv',index=None)

In [3]:
allele_freq_h = pd.read_csv('key_files/merged_hapFIRE_allele_frequency.txt', nrows=1, sep = '\t')

In [4]:
allele_freq_h.columns

Index(['1_1_1', '1_1_2', '1_1_3', '1_1_4', '1_1_5', '1_1_6', '1_1_7', '1_1_8',
       '1_1_9', '1_1_10',
       ...
       '60_1_3', '60_1_4', '60_1_5', '60_1_6', '60_1_7', '60_1_8', '60_1_9',
       '60_1_10', '60_1_11', '60_1_12'],
      dtype='object', length=745)

In [83]:
allele_freq_h = allele_freq_h.T.reset_index()

In [87]:
allele_freq_h[allele_freq_h['index'].isin(last_gen)].index

Index([ 13,  14,  24,  25,  26,  27,  28,  29,  30,  31,
       ...
       735, 736, 737, 738, 739, 740, 741, 742, 743, 744],
      dtype='int64', length=355)

In [77]:
pd.read_csv('key_files/merged_hapFIRE_delta_p.txt',nrows=1,sep='\t',header=None)

,0,1,2,3,4,5,6,7,8,9,...,735,736,737,738,739,740,741,742,743,744
0,0.007952,-0.020186,0.008274,0.014525,0.015809,0.012246,-0.007641,0.080549,0.034804,-0.018595,...,0.057666,-0.028029,-0.000572,-0.035332,-0.034154,-0.004419,0.010854,0.099501,0.144855,0.070575

In [5]:
deltap = dd.read_csv('key_files/merged_hapFIRE_delta_p.txt', sep = '\t', header=None)
deltap.columns = allele_freq_h.columns
deltap=deltap[last_gen]

In [6]:
deltap = deltap.compute() 
deltap = deltap.reset_index(drop=True)

In [8]:
var_pos_grenenet = pd.read_csv('key_files/var_pos_grenenet.csv')

In [15]:
mask = var_pos_grenenet['total_alleles05filter_lastgen'].notna()

In [16]:
mask

0          False
1           True
2          False
3          False
4           True
           ...
3235475    False
3235476    False
3235477    False
3235478     True
3235479     True
Name: total_alleles05filter_lastgen, Length: 3235480, dtype: bool

In [18]:
deltapf = deltap[mask]

In [4]:
pd.read_csv('key_files/delta_p_maf05_mincount05_lastgensamples.csv',nrows=1)

,1_2_2,1_2_3,1_3_1,1_3_4,1_3_5,1_3_6,1_3_7,1_3_8,1_3_9,1_3_10,...,60_1_3,60_1_4,60_1_5,60_1_6,60_1_7,60_1_8,60_1_9,60_1_10,60_1_11,60_1_12
0,0.077353,0.063114,0.482707,0.352325,0.084993,0.114956,-0.172746,0.273725,-0.165205,-0.06881,...,0.003421,-0.047405,0.159179,0.139286,0.182493,-0.031104,0.394335,-0.0248,0.214351,0.331971

In [21]:
deltapf.to_csv('key_files/delta_p_maf05_mincount05_lastgensamples.csv',index=None)