In [ ]:
import subprocess

# Run preproc.py
subprocess.run(["python", "preproc_lfmm.py"])

# Run run_lfmm.R
subprocess.run(["Rscript", "run_lfmm.R"])

In [5]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import dask.dataframe as dd
import os
import dask.dataframe as dd

/home/tbellagio/.local/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [13]:
final_gen = pd.read_csv('final_gen.csv')['sample_name'].to_list()
final_gen.append('0')

In [14]:
path_all_af_indexed = '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/baypass_terminal/merged_hapFIRE_allele_frequency_indexed.csv'

In [10]:
allele_freq = dd.read_csv(path_all_af_indexed, sep = ',', usecols=final_gen)

In [11]:
allele_freq = allele_freq.compute()

In [12]:
n_components = len(allele_freq.columns)

In [ ]:
n_components = len(allele_freq.columns)

scaler = StandardScaler()
scaler.fit(allele_freq)
scaled = scaler.fit_transform(allele_freq)

scaled_allele_freq = pd.DataFrame(scaled, columns=allele_freq.columns)

# Perform PCA
pca = PCA(n_components=n_components)  # Set the desired number of components
pca.fit(scaled_allele_freq)

# Get the transformed data (projected onto the principal components)
transformed_data = pca.transform(scaled_allele_freq)

explain_var_ratio = pca.explained_variance_ratio_

cumulative_variance = np.cumsum(explain_var_ratio)

# Set the desired cumulative explained variance threshold
threshold = 0.96

# Find the number of components that exceed the threshold
num_components = np.sum(cumulative_variance <= threshold) + 1

In [ ]:
# Open the file in write mode and write the integer
with open('LEA_analyses/full/num_components.txt', 'w') as file:
    file.write(str(num_components))

In [ ]:
# Open the file in read mode and read the integer
with open('LEA_analyses/full/num_components.txt', 'r') as file:
    number_from_file = file.read()
    number_as_int = int(number_from_file)

In [ ]:
clim_sites_during_exp = pd.read_csv('/carnegie/nobackup/scratch/tbellagio/grene/data/bioclimvars_experimental_sites_era5.csv')

In [ ]:
sites_af = pd.Series(allele_freq.columns.str.split('_').str[0]).astype(int)

In [ ]:
sites_af.name = 'site'

In [ ]:
env = sites_af.reset_index().merge(clim_sites_during_exp).drop(['index'],axis=1)

In [ ]:
##scale it
for i in env.columns[1:]:
    env[i] = (env[i] - np.mean(env[i])) / np.std(env[i])

In [ ]:
env.to_csv('LEA_analyses/full/environment_lea.csv', sep = ',', index=False)

In [3]:
3000000/30

100000.0

In [15]:
pd.read_csv(path_all_af_indexed,nrows=10,  usecols=final_gen)

,1_2_2,1_2_3,1_3_1,1_3_4,1_3_5,1_3_6,1_3_7,1_3_8,1_3_9,1_3_10,...,60_1_4,60_1_5,60_1_6,60_1_7,60_1_8,60_1_9,60_1_10,60_1_11,60_1_12,0
0,0.008758,0.074036,0.001647,0.031096,0.082510,0.002337,0.007630,0.024883,0.040135,0.001976,...,0.009546,0.037003,0.002243,0.003422,0.033156,0.048429,0.137076,0.182430,0.108151,1_291
1,0.341474,0.327235,0.746828,0.616446,0.349114,0.379077,0.091375,0.537846,0.098916,0.195311,...,0.216716,0.423299,0.403407,0.446614,0.233017,0.658456,0.239321,0.478471,0.596091,1_346
2,0.002089,0.001881,0.000312,0.000288,0.002183,0.000549,0.000693,0.095821,0.001421,0.000134,...,0.001179,0.000452,0.000568,0.000775,0.004815,0.003813,0.001658,0.000284,0.000503,1_349
3,0.112909,0.037417,0.125082,0.000282,0.006610,0.075121,0.002608,0.080393,0.003473,0.001462,...,0.002425,0.001585,0.001520,0.027464,0.009201,0.003361,0.003644,0.001411,0.003389,1_352
4,0.054013,0.020423,0.006074,0.001199,0.178328,0.122217,0.008013,0.098583,0.120582,0.002295,...,0.173450,0.027055,0.003218,0.017458,0.135612,0.016264,0.009464,0.085654,0.012627,1_353
5,0.123593,0.050841,0.062592,0.002276,0.125150,0.008275,0.594746,0.008767,0.023503,0.004233,...,0.007692,0.006626,0.133387,0.017367,0.226834,0.011577,0.021688,0.096677,0.017196,1_363
6,0.011205,0.076021,0.002047,0.031933,0.085963,0.003120,0.009441,0.025593,0.043369,0.002041,...,0.049337,0.127186,0.003473,0.004584,0.136237,0.051577,0.193522,0.183210,0.110149,1_395
7,0.011205,0.076021,0.002047,0.031933,0.085963,0.003120,0.009441,0.025593,0.043369,0.002041,...,0.049337,0.127186,0.003473,0.004584,0.136237,0.051577,0.193522,0.183210,0.110149,1_396
8,0.004834,0.050054,0.001047,0.002162,0.044822,0.079445,0.002606,0.000600,0.008874,0.001635,...,0.010892,0.005150,0.289613,0.042609,0.004496,0.014993,0.186311,0.029888,0.049335,1_419
9,0.188388,0.062459,0.132020,0.001817,0.189384,0.198562,0.012228,0.179952,0.263950,0.004509,...,0.177232,0.029506,0.005611,0.045565,0.146863,0.021919,0.015012,0.088118,0.019011,1_425

In [20]:
# Load the data
gfile_ddf = dd.read_csv(path_all_af_indexed, usecols=final_gen)
# Now repartition if necessary
gfile_ddf = gfile_ddf.repartition(npartitions=30)

In [21]:
!pwd

/carnegie/nobackup/scratch/tbellagio/gea_grene-net

In [22]:
# Specify the output folder
output_folder = 'allele_freq_partitions'

# Create the folder if it doesn't exist
os.makedirs(output_folder, exist_ok=True)

# Save each partition to a separate CSV file
# Files will be named part-0.csv, part-1.csv, ..., part-29.csv
gfile_ddf.to_csv(os.path.join(output_folder, 'allele_freq_part-*.csv'), index=False)

['/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-00.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-01.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-02.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-03.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-04.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-05.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-06.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-07.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-08.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-09.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-10.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-11.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-12.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-13.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-14.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-15.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-16.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-17.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-18.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-19.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-20.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-21.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-22.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-23.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-24.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-25.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-26.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-27.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-28.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions/allele_freq_part-29.csv']

In [17]:
!pwd

/carnegie/nobackup/scratch/tbellagio/gea_grene-net

In [28]:
import subprocess

In [30]:
import shlex

In [36]:
shlex.split(cmd)

['Rscript',
 'run_lfmm.R',
 'allele_freq_part-00.csv',
 '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-00.out']

In [ ]:
scratch/gea_grene-net/allele_freq_partitions

In [37]:
import subprocess
import shlex
import os
path_all_af = '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions'
results_dir = '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full'


for input_file in sorted(os.listdir(path_all_af)):
    if input_file.endswith(".csv"):  # Make sure to process only CSV files
        output_file = os.path.join(results_dir, f"result_{input_file.split('.')[0]}.out")  # Assuming input files are like 'file.csv'
        cmd = f'Rscript run_lfmm.R allele_freq_partitions/{input_file} {output_file}'
        subprocess.run(shlex.split(cmd), check=True)

FileNotFoundError: [Errno 2] No such file or directory: 'Rscript'

In [ ]:
scratch/gea_grene-net/LEA_analyses/full

In [23]:
# Path to the partitions 
path_all_af = '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/allele_freq_partitions'

# Directory setup for results and shell scripts
path_analysis = '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses'
results_dir = '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full'
sh_dir = '/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/shfiles'
os.makedirs(results_dir, exist_ok=True)
os.makedirs(sh_dir, exist_ok=True)

# Function to create and save bash scripts
def create_bash_script(i, input_file):
    output_file = os.path.join(results_dir, f"result_{input_file.split('.')[0]}.out")  # Assuming input files are like 'file.csv'
    print(input_file)
    print(output_file)
    cmd = f'Rscript run_lfmm.R {input_file} {output_file}'
    script_content = f'''#!/bin/bash
#SBATCH --job-name=chain_{i+1}
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=100gb
#SBATCH --cpus-per-task=10
#SBATCH --output={sh_dir}/chain_{i+1}_%j.out
#SBATCH --mail-user=tbellagio@carnegiescience.edu
#SBATCH --mail-type=FAIL

module load python/3.11_conda
conda activate /home/tbellagio/miniforge3/envs/snakemake_pipeline
cd /carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses
{cmd}
'''
    with open(os.path.join(sh_dir, f'chain_{i+1}.sh'), 'w') as f:
        f.write(script_content)

# Read allele frequency files and create scripts
chunk_counter = 0
for file in sorted(os.listdir(path_all_af)):
    if file.endswith(".csv"):  # Make sure to process only CSV files
        create_bash_script(chunk_counter, file)
        chunk_counter += 1

allele_freq_part-00.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-00.out
allele_freq_part-01.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-01.out
allele_freq_part-02.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-02.out
allele_freq_part-03.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-03.out
allele_freq_part-04.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-04.out
allele_freq_part-05.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-05.out
allele_freq_part-06.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-06.out
allele_freq_part-07.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-07.out
allele_freq_part-08.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-08.out
allele_freq_part-09.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-09.out
allele_freq_part-10.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-10.out
allele_freq_part-11.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-11.out
allele_freq_part-12.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-12.out
allele_freq_part-13.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-13.out
allele_freq_part-14.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-14.out
allele_freq_part-15.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-15.out
allele_freq_part-16.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-16.out
allele_freq_part-17.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-17.out
allele_freq_part-18.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-18.out
allele_freq_part-19.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-19.out
allele_freq_part-20.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-20.out
allele_freq_part-21.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-21.out
allele_freq_part-22.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-22.out
allele_freq_part-23.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-23.out
allele_freq_part-24.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-24.out
allele_freq_part-25.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-25.out
allele_freq_part-26.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-26.out
allele_freq_part-27.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-27.out
allele_freq_part-28.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-28.out
allele_freq_part-29.csv
/carnegie/nobackup/scratch/tbellagio/gea_grene-net/LEA_analyses/full/result_allele_freq_part-29.out

In [38]:
!pwd

/carnegie/nobackup/scratch/tbellagio/gea_grene-net

In [ ]:
scratch/gea_grene-net/allele_freq_partitions/allele_freq_part-00.csv

In [41]:
pd.read_csv('allele_freq_partitions/allele_freq_part-00.csv')

,1_2_2,1_2_3,1_3_1,1_3_4,1_3_5,1_3_6,1_3_7,1_3_8,1_3_9,1_3_10,...,60_1_4,60_1_5,60_1_6,60_1_7,60_1_8,60_1_9,60_1_10,60_1_11,60_1_12,0
0,0.008758,0.074036,0.001647,0.031096,0.082510,0.002337,0.007630,0.024883,0.040135,0.001976,...,0.009546,0.037003,0.002243,0.003422,0.033156,0.048429,0.137076,0.182430,0.108151,1_291
1,0.341474,0.327235,0.746828,0.616446,0.349114,0.379077,0.091375,0.537846,0.098916,0.195311,...,0.216716,0.423299,0.403407,0.446614,0.233017,0.658456,0.239321,0.478471,0.596091,1_346
2,0.002089,0.001881,0.000312,0.000288,0.002183,0.000549,0.000693,0.095821,0.001421,0.000134,...,0.001179,0.000452,0.000568,0.000775,0.004815,0.003813,0.001658,0.000284,0.000503,1_349
3,0.112909,0.037417,0.125082,0.000282,0.006610,0.075121,0.002608,0.080393,0.003473,0.001462,...,0.002425,0.001585,0.001520,0.027464,0.009201,0.003361,0.003644,0.001411,0.003389,1_352
4,0.054013,0.020423,0.006074,0.001199,0.178328,0.122217,0.008013,0.098583,0.120582,0.002295,...,0.173450,0.027055,0.003218,0.017458,0.135612,0.016264,0.009464,0.085654,0.012627,1_353
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107725,0.183397,0.185472,0.084145,0.477161,0.127747,0.150111,0.008073,0.001318,0.007777,0.000502,...,0.004246,0.004794,0.015417,0.020751,0.015052,0.015592,0.041060,0.002484,0.259138,1_5117078
107726,0.000909,0.001461,0.000046,0.000073,0.000519,0.000401,0.000386,0.000637,0.000935,0.000061,...,0.080396,0.000454,0.002288,0.225818,0.000937,0.002522,0.008686,0.000321,0.000526,1_5117119
107727,0.000561,0.000937,0.000000,0.000000,0.000267,0.000144,0.000129,0.000492,0.000342,0.000060,...,0.000198,0.023592,0.182511,0.000172,0.000724,0.001617,0.054995,0.000251,0.000137,1_5117510
107728,0.000561,0.000937,0.000000,0.000000,0.000267,0.000144,0.000129,0.000492,0.000342,0.000060,...,0.000198,0.023592,0.182511,0.000172,0.000724,0.001617,0.054995,0.000251,0.000137,1_5117554
107729,0.099845,0.041917,0.024345,0.273833,0.045914,0.007939,0.130641,0.005163,0.057544,0.004188,...,0.005371,0.059252,0.006328,0.011996,0.067411,0.011947,0.013495,0.007968,0.015323,1_5117574

In [39]:
pd.read_csv('LEA_analyses/full/pvalues_allele_freq_part-00.csv')

,Unnamed: 0,Response Y1,Response Y2,Response Y3,Response Y4,Response Y5,Response Y6,Response Y7,Response Y8,Response Y9,...,Response Y107721,Response Y107722,Response Y107723,Response Y107724,Response Y107725,Response Y107726,Response Y107727,Response Y107728,Response Y107729,Response Y107730
0,X1,4.304648e-01,0.780705,0.549447,0.321166,0.952609,0.605179,2.605998e-01,2.605998e-01,0.351662,...,0.899414,0.032515,1.081446e-01,0.991163,6.326759e-02,7.785156e-02,0.866914,0.509853,0.509853,0.899414
1,X2,4.206365e-01,0.110056,0.004556,0.895190,0.939914,0.711109,5.487860e-01,5.487860e-01,0.954003,...,0.003607,0.031053,2.076568e-01,0.941230,1.831385e-01,2.183650e-01,0.089854,0.025775,0.025775,0.003607
2,X3,1.036665e-01,0.457704,0.165962,0.369743,0.325684,0.914788,2.674790e-01,2.674790e-01,0.184007,...,0.661927,0.935973,1.277656e-01,0.774608,3.602078e-01,9.572775e-02,0.569287,0.011459,0.011459,0.661927
3,X4,1.169014e-01,0.618678,0.229812,0.484778,0.440984,0.985694,3.012281e-01,3.012281e-01,0.148800,...,0.592808,0.887257,1.125288e-01,0.758114,3.808255e-01,8.370958e-02,0.695084,0.013834,0.013834,0.592808
4,X5,7.562643e-01,0.299439,0.681738,0.145596,0.609951,0.187959,3.508949e-01,3.508949e-01,0.461811,...,0.046397,0.785325,2.555990e-01,0.874062,5.433627e-01,2.059657e-01,0.149102,0.131225,0.131225,0.046397
5,X6,8.311042e-02,0.214878,0.050765,0.233822,0.145432,0.822576,1.880255e-01,1.880255e-01,0.129777,...,0.997923,0.874432,2.871768e-01,0.840244,6.452922e-01,2.423137e-01,0.365845,0.002088,0.002088,0.997923
6,X7,8.909396e-02,0.592619,0.302624,0.343960,0.397208,0.979735,1.866383e-01,1.866383e-01,0.301091,...,0.567577,0.493160,8.878616e-02,0.744115,2.412931e-01,6.348825e-02,0.703556,0.024716,0.024716,0.567577
7,X9,5.785783e-01,0.825119,0.757295,0.969826,0.669876,0.239994,8.872028e-01,8.872028e-01,0.705520,...,0.720460,0.029555,8.490610e-04,0.614331,1.140943e-03,3.161726e-04,0.149918,0.443426,0.443426,0.720460
8,X10,8.175309e-01,0.879843,0.218689,0.130291,0.949343,0.566724,9.439641e-01,9.439641e-01,0.635598,...,0.535433,0.025139,5.267573e-02,0.918302,1.123976e-01,4.921572e-02,0.803609,0.224023,0.224023,0.535433
9,X11,6.198959e-01,0.536610,0.640076,0.098601,0.792641,0.301823,3.931514e-01,3.931514e-01,0.436565,...,0.002763,0.173562,2.168308e-01,0.856372,4.068162e-01,1.827137e-01,0.053439,0.421932,0.421932,0.002763
10,X12,8.139856e-01,0.180066,0.326759,0.113401,0.687744,0.244186,7.312511e-01,7.312511e-01,0.459720,...,0.385944,0.630976,2.204396e-01,0.924809,4.465808e-01,1.676342e-01,0.397332,0.040453,0.040453,0.385944
11,X13,6.986192e-01,0.691074,0.250732,0.158613,0.741402,0.683699,9.977621e-01,9.977621e-01,0.893556,...,0.310394,0.085670,4.648899e-02,0.759289,9.938082e-02,4.077681e-02,0.862049,0.467371,0.467371,0.310394
12,X14,8.350095e-01,0.896288,0.214412,0.145938,0.678691,0.773895,7.585292e-01,7.585292e-01,0.431601,...,0.897095,0.569178,1.171616e-01,0.614862,7.626063e-02,1.082101e-01,0.769672,0.394126,0.394126,0.897095
13,X15,7.363507e-01,0.213949,0.047243,0.116116,0.590968,0.871817,6.969537e-01,6.969537e-01,0.696394,...,0.102795,0.003468,5.788095e-02,0.716950,1.091561e-01,4.850369e-02,0.627010,0.527260,0.527260,0.102795
14,X16,9.818962e-01,0.764787,0.351286,0.702843,0.709137,0.197115,7.666485e-01,7.666485e-01,0.232365,...,0.803274,0.703521,5.936549e-01,0.705912,9.586599e-01,5.872123e-01,0.621089,0.032352,0.032352,0.803274
15,X17,6.736929e-01,0.792487,0.088552,0.333339,0.675405,0.533911,7.935091e-01,7.935091e-01,0.561379,...,0.179439,0.058194,2.807763e-01,0.568306,5.899048e-01,2.736464e-01,0.861982,0.312666,0.312666,0.179439
16,X18,8.041687e-01,0.067005,0.015682,0.568773,0.509812,0.890920,3.893335e-01,3.893335e-01,0.579848,...,0.295144,0.096777,5.858049e-01,0.730541,9.861469e-01,5.749060e-01,0.863124,0.017074,0.017074,0.295144
17,X19,9.617729e-01,0.111919,0.039709,0.266888,0.626702,0.804974,4.707298e-01,4.707298e-01,0.999950,...,0.525261,0.215665,6.352627e-01,0.931449,5.587894e-01,6.581046e-01,0.299679,0.028914,0.028914,0.525261
18,X20,3.337807e-01,0.625668,0.590187,0.545542,0.317410,0.704825,9.699635e-01,9.699635e-01,0.444566,...,0.488296,0.502418,4.773979e-01,0.532769,6.393507e-02,4.149729e-01,0.468780,0.035579,0.035579,0.488296
19,X1.1,2.475421e-08,0.001088,0.673541,0.448502,0.332369,0.940466,5.182279e-07,5.182279e-07,0.435063,...,0.650513,0.094107,1.856222e-08,0.890828,4.644098e-07,8.039414e-09,0.343345,0.395400,0.395400,0.650513