In [1]:
import pandas as pd
import pickle

In [2]:
tair = pd.read_csv('../key_files/TAIR10_GFF3_genes.gff', sep = '\t',header=None)

In [3]:


# Read the file
file_path = '../key_files/TAIR10_GFF3_genes.gff'
gff_df = pd.read_csv(file_path, sep='\t', comment='#', header=None)

# Assigning appropriate column names for the GFF3 file format
gff_df.columns = ['seqname', 'source', 'feature', 'start', 'end', 'score', 'strand', 'frame', 'attribute']

In [ ]:
gff_df = gff_df[gff_df['seqname'].isin(['Chr1', 'Chr2', 'Chr3', 'Chr4', 'Chr5'])]

gff_df['chrom'] = gff_df['seqname'].str.replace('Chr', '')

In [6]:
gff_df = gff_df.reset_index()

In [7]:
dict_snps = '../key_files/var_pos_grenenet.csv'
dict_snps = pd.read_csv(dict_snps)

In [8]:
gff_df['gene_id'] = gff_df['attribute'].str.split(';').str[0].replace('ID=', '')

In [9]:
# Split the 'id' column into 'chrom' and 'pos'
dict_snps[['chrom', 'pos']] = dict_snps['id'].str.split('_', expand=True)
dict_snps['pos'] = dict_snps['pos'].astype(int)  # Ensure position is an integer for comparison

In [10]:
#dict_snps = dict_snps[dict_snps['maf05filter'].notna()].reset_index(drop=True)

In [11]:
dict_snps['chrom'] = dict_snps['chrom'].astype(int)

In [12]:
gff_df['chrom'] = gff_df['chrom'].astype(int)

In [15]:
from tqdm import tqdm

# Initialize tqdm to add progress to pandas operations
tqdm.pandas()

# Create a function to assign a gene based on chrom and position
def assign_gene(row, genes_df):
    chrom = row['chrom']
    pos = row['pos']
    
    # Filter genes that match the chromosome and where the position is between the gene's start and end
    gene_match = genes_df[(genes_df['chrom'] == chrom) & (genes_df['start'] <= pos) & (genes_df['end'] >= pos)]
    
    # If a match is found, assign the gene's ID; otherwise, return NaN
    if not gene_match.empty:
        return gene_match.iloc[0]['gene_id']  # You can modify this to return specific attributes (e.g., 'ID')
    else:
        return None

# Apply the function with a progress bar
dict_snps['assigned_gene'] = dict_snps.progress_apply(assign_gene, axis=1, genes_df=gff_df)

100%|██████████| 3235480/3235480 [49:45<00:00, 1083.58it/s]

In [71]:
dict_snps['assigned_gene'].value_counts(dropna=False)

assigned_gene
None            522758
ID=AT5G24740       548
ID=AT4G13750       303
ID=AT1G58060       299
ID=AT5G17410       286
                 ...
ID=AT4G38405         1
ID=AT1G20823         1
ID=AT1G20875         1
ID=AT3G15111         1
ID=AT1G24390         1
Name: count, Length: 25673, dtype: int64

In [72]:
dict_snps

,id,pos,chrom,maf05filter,total_alleles05filter_firstgen,total_alleles05filter_lastgen,assigned_gene
0,1_346,346,1,1_346,1_346,1_346,None
1,1_353,353,1,1_353,1_353,1_353,None
2,1_363,363,1,1_363,1_363,1_363,None
3,1_395,395,1,1_395,1_395,1_395,None
4,1_396,396,1,1_396,1_396,1_396,None
...,...,...,...,...,...,...,...
1147887,5_26975078,26975078,5,5_26975078,5_26975078,5_26975078,None
1147888,5_26975121,26975121,5,5_26975121,5_26975121,5_26975121,None
1147889,5_26975148,26975148,5,5_26975148,5_26975148,5_26975148,None
1147890,5_26975272,26975272,5,5_26975272,5_26975272,5_26975272,None
1147891,5_26975288,26975288,5,5_26975288,5_26975288,5_26975288,None

In [73]:
dict_snps.to_csv('../key_files/var_pos_grenenet_annotated.csv',index=False)

In [74]:
dict_snps

,id,pos,chrom,maf05filter,total_alleles05filter_firstgen,total_alleles05filter_lastgen,assigned_gene
0,1_346,346,1,1_346,1_346,1_346,None
1,1_353,353,1,1_353,1_353,1_353,None
2,1_363,363,1,1_363,1_363,1_363,None
3,1_395,395,1,1_395,1_395,1_395,None
4,1_396,396,1,1_396,1_396,1_396,None
...,...,...,...,...,...,...,...
1147887,5_26975078,26975078,5,5_26975078,5_26975078,5_26975078,None
1147888,5_26975121,26975121,5,5_26975121,5_26975121,5_26975121,None
1147889,5_26975148,26975148,5,5_26975148,5_26975148,5_26975148,None
1147890,5_26975272,26975272,5,5_26975272,5_26975272,5_26975272,None
1147891,5_26975288,26975288,5,5_26975288,5_26975288,5_26975288,None

In [ ]:
genes_df = gff_df.copy()

In [53]:
for index, row in dict_snps1_test.iterrows():

    chrom = row['chrom']
    pos = row['pos']
    
    gene_match = genes_df[(genes_df['chrom'] == chrom) & (genes_df['start'] <= pos) & (genes_df['end'] >= pos)]
    print(gene_match)

Empty DataFrame
Columns: [index, seqname, source, feature, start, end, score, strand, frame, attribute, chrom, gene_id]
Index: []
Empty DataFrame
Columns: [index, seqname, source, feature, start, end, score, strand, frame, attribute, chrom, gene_id]
Index: []
Empty DataFrame
Columns: [index, seqname, source, feature, start, end, score, strand, frame, attribute, chrom, gene_id]
Index: []
Empty DataFrame
Columns: [index, seqname, source, feature, start, end, score, strand, frame, attribute, chrom, gene_id]
Index: []
Empty DataFrame
Columns: [index, seqname, source, feature, start, end, score, strand, frame, attribute, chrom, gene_id]
Index: []

In [58]:
genes_df[(genes_df['chrom'] == chrom) & (genes_df['start'] <= pos) & (genes_df['end'] >= pos)]

Empty DataFrame
Columns: [index, seqname, source, feature, start, end, score, strand, frame, attribute, chrom, gene_id]
Index: []

In [55]:
pos

5685

In [41]:
dict_snps1_test

,id,pos,chrom,maf05filter,total_alleles05filter_firstgen,total_alleles05filter_lastgen,assigned_gene
28,1_4648,4648,1,1_4648,1_4648,1_4648,None
29,1_4654,4654,1,1_4654,1_4654,1_4654,None
30,1_4880,4880,1,1_4880,1_4880,1_4880,None
31,1_5427,5427,1,1_5427,1_5427,1_5427,None
32,1_5685,5685,1,1_5685,NaN,1_5685,None

In [31]:
dict_snps.head(1000).apply(assign_gene, axis=1, genes_df=gff_df)

0      None
1      None
2      None
3      None
4      None
       ...
995    None
996    None
997    None
998    None
999    None
Length: 1000, dtype: object

In [12]:
genomewide_partition_index.columns = ['chrom', 'start', 'end']

NameError: name 'genomewide_partition_index' is not defined